<?php

/**
 * @file
 * farmOS ledger module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function farm_ledger_theme() {
  return [
    'quantity__price' => [
      'render element' => 'elements',
      'base hook' => 'quantity',
    ],
  ];
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function farm_ledger_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {

  // Bail if not a price quantity inline entity form.
  if ($entity_form['#entity_type'] !== 'quantity' || $entity_form['#bundle'] !== 'price') {
    return;
  }

  // Hide the measure field.
  $entity_form['measure']['#access'] = FALSE;

  // Hide the value field. It is auto-populated from the unit_price and
  // unit_quantity fields when the quantity is saved.
  $entity_form['value']['#access'] = FALSE;
}
